// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PublicCalendarController from "./public_calendar_controller"
application.register("public-calendar", PublicCalendarController)

import QuoteFormController from "./quote_form_controller"
application.register("quote-form", QuoteFormController)
